eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8097/eureka"
      
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect